server:
  port: 8760

spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://192.168.1.150:8759/realms/astroflix}
          jwk-set-uri: ${JWK_SET_URI:http://192.168.1.150:8759/realms/astroflix/protocol/openid-connect/certs}
  cloud:
    gateway:
      routes:
        - id: account-route
          uri: lb://account
          predicates:
            - Path=/account/**
        - id: media-route
          uri: lb://media
          predicates:
            - Path=/media/**
  main:
    web-application-type: reactive

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

cors:
  origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}